# An example of how to use FileReaderGenerator.

/det/select Box

/gen/select file_reader

# The pathname parameter should be a text file with seven columns,
# representing: PDG ID; initial x, y, and z coordinates; and initial x, y, z
# components of the momentum of the particle, respectively. Each row
# corresponds to one particle and one event.

/gen/file_reader/pathname {pathname}

# The number of events here must be equal to the number of rows in the file.

/run/beamOn 2 
